export default {
	SHOW_EDIT_FORM_MODAL: 'SHOW_EDIT_FORM_MODAL',
	HIDE_EDIT_FORM_MODAL: 'HIDE_EDIT_FORM_MODAL',
	
	SPRINTSTASKPANEL:'SPRINTSTASKPANEL',
 
	FETCH_TASKS: 'FETCH_TASKS',
	FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
	FETCH_TASKS_ERROR: 'FETCH_TASKS_ERROR',
	
	CREATE_DRAFT_TASK: 'CREATE_DRAFT_TASK',
	UPDATE_DRAFT_TASK: 'UPDATE_DRAFT_TASK',
	
	CREATE_TASK: 'CREATE_TASK',
	CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
	CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',
	
	UPDATE_TASK: 'UPDATE_TASK',
	UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
	UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',
	
	DELETE_TASK: 'DELETE_TASK',
	DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
	DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',
	
	UPDATE_TASK_STATUS: 'UPDATE_TASK_STATUS',
	UPDATE_TASK_POSITION: 'UPDATE_TASK_POSITION',
	
	PERSIST_TASK_DRAG: 'PERSIST_TASK_DRAG',
	PERSIST_TASK_DRAG_SUCCESS: 'PERSIST_TASK_DRAG_SUCCESS',
	PERSIST_TASK_DRAG_ERROR: 'PERSIST_TASK_DRAG_ERROR',
	
	CREATE_USER: 'CREATE_USER',
	CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
	CREATE_USER_ERROR: 'CREATE_USER_ERROR',
	
	UPDATE_USER: 'UPDATE_USER',
	UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
	UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
	
	DELETE_USER: 'DELETE_USER',
	DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
	DELETE_USER_ERROR: 'DELETE_USER_ERROR',	
};